export const links = {
    base: '/',
    admin: '/admin',
    signIn: '/sign-in',
    signUp: '/sign-up',
    executor: '/sign-up/executor/',
    customer: '/sign-up/customer/',
    emailVerification: '/sign-up/email-verification',
    signUpEmail: '/sign-up/email',
    changePassword: '/sign-up/change-password',
    successfulSignUp: '/api/auth/verify-email/:id/:token/',
    clientInfoPage: '/client',
    clientInfoForm: '/client/form',
    freelancerInfoForm: '/freelancer',
    mainPageFreelancer: '/freelancer/main',
    mainPageClient: '/client/main', 
    workDetails: '/client/workDetails',
    freelancerDetails: '/freelancer/freelancerDetails', //not ready
    clientProfilePage: '/client/profile',
    freelancerProfilePage: '/freelancer/profile',
    clientPostPage: '/client/post',
    freelancerSearchPage: '/freelancer/search', 
    clientSearchPage: '/client/search',
    jobDetails: '/job-details',
    saved: '/freelancer/saved',
    waiting: '/freelancer/waiting',
    freelancerProfilePageCustomer: '/freelancer/custprofile',
    profileSettings: '/profile-settings', 
    modalExecutor: '/modal-executor',
    modalCustomer: '/modal-customer',
    logInPageChecked: '/sign-in/checking',
    listOfJob: '/client/listOfJob',
    clientFeedbackPage: '/clientfeedbackpage',
    clientFeedbackPagesecond: '/clientfeedbackpagesecond'
}